### ISSUE TITLE
Add option to set metadata per request

### ISSUE THREAD

**Issue by ghostbuster91** [scalapb/zio-grpc#119]
According to grpc docummentation

> Metadata is information about a particular RPC call (such as authentication details) in the form of a list of key-value pairs, where the keys are strings and the values are typically strings, but can be binary data. Metadata is opaque to gRPC itself - it lets the client provide information associated with the call to the server and vice versa.

https://grpc.io/docs/what-is-grpc/core-concepts/#metadata

The key here is "Metadata is information about a **particular** RPC call"

So, there should be a way to pass different metadata for each rpc call.

Akka implementation of grpc supports that - https://doc.akka.io/docs/akka-grpc/current/client/details.html#request-metadata

**Comment by thesamet** [comment]
Sure, we can build different APIs to accomplish this. What is the use case you have that requires a different metadata for each call?

**Comment by ahjohannessen** [comment]
fs2-grpc does this. Useful for tracing, auth and so on.

**Comment by thesamet** [comment]
I am thinking of making it possible to get the metadata from the environment, in order to not break the API and keep the interface similar to the server:

```
client.unaryRequest(foo).provide(Has(metadata))
```

Thoughts?

**Comment by ahjohannessen** [comment]
@thesamet So the generated code does not change, right? Then that metadata is still `Metadata` / `SafeMetadata`? Or can it be some thing like `ZIO[A, Error, Metadata]` and ZIO[Metadata, Error, Metadata] ?

**Comment by thesamet** [comment]
@ahjohannessen , Yes, we could do that too - the client can have a function that tells it how to get the metadata from the environment.

**Comment by thesamet** [comment]
I pushed a commit which offers a simpler solution: if you have a client, you could do:

```
client.withMetadata(metadata).request(params)
```

**Comment by ahjohannessen** [comment]
@thesamet I suppose the overhead of `new ServiceStub` per call is not big when doing `withMetadat/M`? Otherwise that is very useful due to the ability pass tokens and similar.

**Comment by ghostbuster91** [comment]
IMO it is strange to require users to build a new serviceStub each time they make a call (assuming that each call takes different metadata). I think that it is better to break things in order to provide consistent and developer friendly api than to try maintaining backward compatibility, at least given the early stage of the project. 

I am not a zio expert but it seems more zio-ish to pass it through environment (`R`).

**Comment by thesamet** [comment]
In terms of performance, creating a stub is only another object allocation. The overhead is negligible: sending a single RPC involves many allocations to all sorts of short-lived helper classes both in ZIO gRPC and grpc-java.

The current API `(withMetadta)` is analogous to the `attachHeaders` method in [MetadataUtils](https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/MetadataUtils.html#attachHeaders-T-io.grpc.Metadata-).

It turns out the client already accepted metadata in an effectful form, so I [updated it](https://github.com/scalapb/zio-grpc/commit/da0955777a8cb4f141c8cb1d4d829faae6f202fd#diff-d25d5f517f2bb8794903e804bbbde387L313-R321) to take a `Context` environment.

This results in three ways to provide per-request metadata. You can see the three ways in the [HelloWorldClientMetadata example]( https://github.com/scalapb/zio-grpc/blob/master/examples/src/main/scala/zio_grpc/examples/helloworld/HelloWorldClientMetadata.scala)

**Comment by ghostbuster91** [comment]
Awesome, thanks for the explanation and examples, I think that it should cover most of the cases.

**Comment by thesamet** [comment]
I believe this issue can be resolved. Feel free to open another issue if there are still any gaps.
