### ISSUE TITLE
Unused import

### ISSUE THREAD

**Issue by octavz** [scalapb/zio-grpc#140]
Hi,

I get an warning in the generated code

```
ZioDataService.scala:3:23: Unused import
[error] import scala.language.implicitConversions
```

This will not allow met to use `-Xfatal-warnings` flag.

Thank You.

**Comment by thesamet** [comment]
This import is required to avoid a compiler warning about implicit conversion for the line that starts with:

```
implicit def ops[R, C](service:
```

Can you provide a minimal example project that demonstrates this problem? (The issue doesn't mention scala version, zio-grpc version, scala options in use - so hard to help further)

**Comment by octavz** [comment]
Here, https://github.com/octavz/grpc-test

This doesn't build for me. 

Thank you.

**Comment by thesamet** [comment]
I suspect that this is because you are passing the following scalacOption flag: ```"-language:implicitConversions", //Allow definition of implicit functions called views```

Can you try removing it?

**Comment by thesamet** [comment]
Confirmed that if the `-language:implicitConversions` flag is removed then it compiles cleanly. Note that the line `import scala.language.implicitConversions` can't be removed since most users don't use `-language:implicitConversions` and they would get a different warning. Our goal is to get the generated code to compile cleanly with the default compiler options.

My suggestion to you would be create an sbt subproject only for the protos and the generated code and use standard compiler options for that subproject.

**Comment by octavz** [comment]
Thank you, clear explanation. Closing it.
