### ISSUE TITLE
Example uses weird version

### ISSUE THREAD

**Issue by borissmidt** [scalapb/zio-grpc#172]
Hey i wanted to try out this grpc library. But sadly i had a binary incompatiblity with version 0.4.0.  
it couldn't find `Stream.from(qeueu:Queue) ` 

So i upgraded the library to 0.4.1 but that didn't work either and that even broke the server but this wan't listed on your page. 

Also once you start coding a server and clean the generated code then the instruction `sbt compile` doesn't work anymore. 
here is he project i tried to make out: 
[zio-learning.zip](https://github.com/scalapb/zio-grpc/files/5655632/zio-learning.zip)

So i think the guide could use some extra explanations. Also i didn't find any way to put my proto's in my `src/resource` folder instead of `src/protofile` .

**Comment by thesamet** [comment]
Hi Boris, the zip file you attached seems to be empty. It would be really helpful if you describe specifically what you mean when you write "broke the server", or "doesn't work anymore" - please write the exact steps you were taking (having the example project would be great), and the specific error messages that you are seeing. Otherwise, it's hard to help.

> But sadly i had a binary incompatiblity with version 0.4.0. it couldn't find Stream.from(qeueu:Queue)
`Stream.from` is a ZIO function: it's unclear how an upgrade of zio-grpc impacted that. To demonstrate this issue, it would be helpful to have a project that an be broken or fixed by adjusting the zio-grpc version number.

Finally, to change where ScalaPB looks for protos, look for `PB.protoSources` in [sbt-protoc main page](https://github.com/thesamet/sbt-protoc).

**Comment by borissmidt** [comment]
Oke so Stream.from is a ZIO function changed that it included a chunk size now so it is missing a parameter in your project if you are on a too new version of ZIO. 
after upgrading it fails on another binary compatibility error but now with the grpc library. 
I forgot the -r in the zip command sorry for that. 
[grpc-project.zip](https://github.com/scalapb/zio-grpc/files/5657499/grpc-project.zip)

**Comment by thesamet** [comment]
In 1251457 I updated the version of the example and README to the latest (0.4.2).

**Comment by thesamet** [comment]
I think all the issues you have raised are addressed with the latest version of zio-grpc (0.4.2) and the updated version information in the example project and README. Please feel free to open additional issues if you come across any issue.
