### ISSUE TITLE
Generated code can trigger `parameter value evidence$3 in method live is never used` compiler warning

### ISSUE THREAD

**Issue by shonfeder** [scalapb/zio-grpc#396]
I hit this with generated code from the following proto spec:

```protobuf
syntax = "proto3";

option java_multiple_files = true;
option java_package = "my.package.here";
option java_outer_classname = "ClassName";
option objc_class_prefix = "TEP";

package hai;

service TransExplorer {
  rpc OpenConnection (ConnectRequest) returns (Connection);
}

message ConnectRequest {
}

message Connection {
  string id = 1;
}
```

I found a workaround to silence the warning from this SO answer: https://stackoverflow.com/a/66354074/1187277 . They also mention hitting the exact same warning with zio-grpc.

It'd be nice if this warning were silenced in the source, but at least I thought it would be helpful to record the workaround here for future seekers. Add the following scalac options to your SBT config to silence warnings for generated code:

```scala
ThisBuild / scalacOptions += "-Wconf:src=src_managed/.*:silent"
```

**Comment by thesamet** [comment]
Generated code may result in compiler warnings. Since we are supporting multiple major versions of Scala, introducing logic to completely suppress warnings adds a lot of noise to our own code. My recommendation would be to suppress like you did, or have the generated code compile in a different sub-project with more relaxed warning settings.
