### ISSUE TITLE
Generate methods using ZIO environment

### ISSUE THREAD

**Issue by ghostdogpr** [scalapb/zio-grpc#43]
It would be nice to be able to generate methods that return `ZIO[R, Status, ?]` instead of just `IO[Status, ?]`. Maybe something similar to `WithContext`? `WithEnvironment[R]`?

What would be even nicer is to combine both and get the context that way: `ZIO[Context with R, Status, ?]`.

**Comment by thesamet** [comment]
Thanks for the feedback. Actually, the initial implementation I put together had methods that return `ZIO[R, Status, ?]`. It looks like the [module recipe](https://zio.dev/docs/howto/howto_use_layers#the-module-recipe) that is recently promoted with ZIO encourages us to pass dependencies to modules through parameters, so those signatures have been removed for simplicity.

I am fine with bringing this back, looks like the ticket already got a few thumb ups, but I want to understand the need better. Aren't we essentially saying that the general recommendation for writing modules doesn't apply when building grpc services? If so, why is that?

I am looking for additional specific proposals on how to structure the generated code:
1. Should we combine `WithContext` and `WithEnvironment` to a single thing (`WithContextAndEnvironment`)? Otherwise we'd have 4 versions of the generated signatures.
2. How do we pick whether to pass the Context as a parameter or through the environment? Looks like this would add 2 more combinations to the previous 4: WithContextAsEnvironment, and WithContextAsEnvironmentWithEnvironment...

**Comment by ghostdogpr** [comment]
I think we usually want to eliminate dependencies from our methods in regular modules because they get passed around and called from other code, but the gRPC services are the top layer of the application so it's fine that they depend on R since it won't affect the rest of the code.

The main goal is actually to reduce boilerplate: I have a lot of services and for each of them I need to make a class and an `apply` method with a big `ZLayer.fromServices` block to extract my dependencies and feed them to the class. If methods were taking R, all this code could go away (given that `ZBindableService` would support R too) and I could provide my dependencies for all the services at once when building the server.

Regarding variants of generated code:
- I think you can generate all methods with R and use aliases for the versions without environment that points to the former with R = Any.
- About Context by parameter vs environment, could it be an option of the generator? I don't think you'd need both at the same time. I'd favor the environment one as the default since it's more ZIO idiomatic.

Does that make sense?

**Comment by thesamet** [comment]
Done! I added support for using environments in generated services. One caveat is that both the environment and the context must be `<: Has[_]`. The reason is that we need to transform the environment from `R with Metadata` to `R with UserContext` using a function `Metadata => ZIO[R, Status, UserContext]` to allow the user to interpret metadata. Feedback is welcome.

Example usage: https://github.com/scalapb/zio-grpc/blob/master/e2e/src/test/scala/scalapb/zio_grpc/EnvSpec.scala

**Comment by ghostdogpr** [comment]
Nice! I will try it today (I guess it's in the latest snapshot?) and give you my feedback.

**Comment by thesamet** [comment]
Yes, there's a snapshot for each commit.

**Comment by ghostdogpr** [comment]
I think I'm missing an implicit def for `bindableService` that accepts an `R` and where `bindService` would return a `URIO[R, ServerServiceDefinition]`. I'm using `ZBindableService.serviceDefinition` because I'm attaching some Java interceptors to it.

**Comment by ghostdogpr** [comment]
By the way the only reason I still use a Java interceptor is that I need a couple things on `ServerCall` (that are not in `Metadata`), namely `getMethodDescriptor` and `getAttributes`. I don't think there's a way to access it otherwise but let me know if there's a way.

**Comment by ghostdogpr** [comment]
I can do this and it works, but it would save 2 lines if `ZBindableService` was supporting `R`:
```scala
ZIO.environment[R].flatMap(env =>
  ZBindableService.serviceDefinition(
    ZMyService.provide(new MyServiceImpl(), env.get)
  )
)
```

**Comment by thesamet** [comment]
Added R support to ZBindableService in ee290f44e4a59978a306b6f7d1d13b277d31169f

**Comment by thesamet** [comment]
Note that the names may slightly change at this point (that `Aux` in `ZBindableService` is probably not really necessary, I tried to keep the type with one hole)

**Comment by ghostdogpr** [comment]
It seems to work. It fails to infer types properly on `serviceDefinition` but it works if I mark them explicitly. Not sure if it's possible to make it better though.

**Comment by ghostdogpr** [comment]
Maybe generate a helper for `serviceDefinition` in each service that is properly tagged?

**Comment by thesamet** [comment]
> It fails to infer types properly on serviceDefinition but it works if I mark them explicitly. Not sure if it's possible to make it better though.

Can you create a test case that demonstrates this?

**Comment by ghostdogpr** [comment]
Oh, it was only IntelliJ 🤦 It compiles well!

**Comment by ghostdogpr** [comment]
Closing this issue then, thanks a lot!
