### ISSUE TITLE
Can't make JS part of the FullApp example work

### ISSUE THREAD

**Issue by sergeda** [scalapb/zio-grpc#489]
There is no instruction how to run the fullapp example, but I figured out that server runs on the port 9000 by default.
But client was pointing to port 9090 and web client to port 8080 for some reason.
After changing the port to 9000 in all clients - java client ran fine. But web client is not working. In the web console it prints "Hello" and that's all.

**Comment by thesamet** [comment]
Thanks for calling it out - doc for running the fullapp are missing. You haven't mentioned envoyproxy, so that's likely to be the missing piece. envoyproxy needs to run on the server-side and forward the client's grpc-web requests to the actual grpc server. There's an unmerged PR that has an envoyproxy config, but I haven't tested it.

**Comment by sergeda** [comment]
Envoy proxy is needed only if we use same port for both of the servers. The problem is - there is no request from the generated js file: [DevTools](https://pasteboard.co/fQ6xUhIPKaHU.jpg)

**Comment by sergeda** [comment]
After adding this line to the web client's code `.catchAllDefect(e => printLine(s"Defect: ${e.getMessage()}") *> ZIO.attempt(e.printStackTrace()))` I got this error `Defect: No status found for code INTERNAL` in the console:
[Screenshot](https://pasteboard.co/7FVoBxMzFb1w.jpg)

**Comment by thesamet** [comment]
Sounds like something stopped working with the latest Scala.js version. We don't have a CI test for Scala.js so it's certainly a possibility. I'll take a look this week.

**Comment by thesamet** [comment]
Turns out we broke Scala.js in a recent change. I've cut 0.6.0-rc4 that contains a fix, as well as a [README.md](https://github.com/scalapb/zio-grpc/blob/master/examples/fullapp/README.md) that explains how to run the fullapp.

Note that 0.6.0-rc4 contains some breaking changes to the generated API (the error type is now `StatusException` instead of `Status`).

**Comment by andrew-selvia** [comment]
Thank you for the update! I’ll validate tomorrow evening.

**Comment by andrew-selvia** [comment]
Confirmed! Everything's working now. Thank you @thesamet 🙏🏻
