### ISSUE TITLE
Installation instructions don't mention Grpc / true neither dependency on scalapb-runtime-grpc at compile

### ISSUE THREAD

**Issue by ragb** [scalapb/zio-grpc#94]
Will following instructions in the [Installation page](https://scalapb.github.io/zio-grpc/docs/installation/) just realized that Grpc descriptors were not being generated.
After some time kinda lost, just follow the build.sbt in the examples and the reference to `Grpc = true` was there, despite no reference to it anywhere on the docs.

Will this and dependency on scalapb-runtime-grpc the service code generated by Zions-grpc-codegen gets compiled.

Creating a PR for this in a moment.

**Comment by thesamet** [comment]
Sorry for the confusion, and thanks for fixing the docs. In sbt, the default value for grpc would normally be `true`, however in 0.10.5-0.10.7 we had a regression where it defaulted to false (https://github.com/scalapb/ScalaPB/issues/879). It wouldn't hurt to leave grpc=true set explicitly in the docs (as done in this PR), since people may still end up being on one of the versions where it is broken.
